<?php

use App\Models\User;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Add a public slug to agent_profiles for URLs like /agents/{slug}.
     *
     * Slug auto-generated by spatie/laravel-sluggable (HasSlug trait) on create.
     * Existing rows backfilled from the associated user's decrypted name,
     * ensuring demo data has working public agent URLs immediately.
     */
    public function up(): void
    {
        Schema::table('agent_profiles', function (Blueprint $table) {
            $table->string('slug')->nullable()->unique()->after('user_id');
        });

        // Backfill existing rows — load User via Eloquent so CipherSweet decrypts name.
        $profiles = DB::table('agent_profiles')->select('id', 'user_id')->get();

        foreach ($profiles as $row) {
            $user = User::find($row->user_id);

            if ($user === null) {
                continue;
            }

            $base = Str::slug($user->name) ?: 'agent';
            $slug = $base;
            $suffix = 1;

            while (DB::table('agent_profiles')->where('slug', $slug)->exists()) {
                $slug = "{$base}-{$suffix}";
                $suffix++;
            }

            DB::table('agent_profiles')->where('id', $row->id)->update(['slug' => $slug]);
        }
    }

    public function down(): void
    {
        Schema::table('agent_profiles', function (Blueprint $table) {
            $table->dropUnique(['slug']);
            $table->dropColumn('slug');
        });
    }
};
