<?php

namespace App\Actions\Property;

use App\Models\Property;
use App\Models\User;

/**
 * Handles the creation of a new property listing.
 *
 * Slug is auto-generated by spatie/laravel-sluggable via HasSlug trait on the model.
 * Sets published_at when publishing, assigns the property to the authenticated agent,
 * and auto-resolves lat/lng via Nominatim when coordinates are not provided.
 */
class CreatePropertyAction
{
    public function __construct(
        private readonly ResolvePropertyCoordinatesAction $resolveCoordinates,
    ) {}

    /**
     * @param  array<string, mixed>  $data  Validated property attributes.
     */
    public function execute(User $user, array $data): Property
    {
        if (($data['is_published'] ?? false) && empty($data['published_at'])) {
            $data['published_at'] = now();
        }

        if (empty($data['latitude']) || empty($data['longitude'])) {
            $coords = $this->resolveCoordinates->execute($data);
            if ($coords !== null) {
                $data['latitude'] = $coords['lat'];
                $data['longitude'] = $coords['lng'];
            }
        }

        $property = new Property;
        $property->user_id = $user->id;
        $property->fill($data);
        $property->save();

        return $property;
    }
}
