<?php

namespace App\Actions\Property;

use App\Models\Property;
use App\Models\User;

/**
 * Handles the creation of a new property listing.
 *
 * Slug is auto-generated by spatie/laravel-sluggable via HasSlug trait on the model.
 * Sets published_at when publishing, and assigns the property to the authenticated agent.
 */
class CreatePropertyAction
{
    public function execute(User $user, array $data): Property
    {
        if (($data['is_published'] ?? false) && empty($data['published_at'])) {
            $data['published_at'] = now();
        }

        $property = new Property;
        $property->user_id = $user->id;
        $property->fill($data);
        $property->save();

        return $property;
    }
}
